#!/bin/bash

# compares fonts in new directory with fonts as hosted on Google Fonts to any show changes
# 
# Example:
# diff-fonts IBM-Plex-Sans/fonts/complete/ttf

set -e

# get args
fontsBefore="$1"

# make list of TTFs
ttfs=$(ls $fontsBefore/*.ttf)

# get font family name for "out" folder
for ttf in $ttfs; do
    filename=$(basename $ttf)
    fontname=${filename/"-"*/""}
done

# run QA script
gftools qa -gf --diffenator $ttfs -o $fontname-diffs